services:
  watchlist:
    image: ghcr.io/lancetm714/shopgoodwill-watchlist:latest
    container_name: goodwill-watchlist
    ports:
      - "6518:6518"
    volumes:
      - ./data:/app/data
    restart: unless-stopped